[auth]
redirect_uri = "http://127.0.0.1:5173/oauth2callback"
cookie_secret = "YOUR_RANDOM_STRING_HERE"

[auth.keycloak]
client_id = "react-dev"
client_secret = "Pv9Qd8HQACPc8UzUV3MzNibhza0DHXBj"
server_metadata_url = "http://192.168.5.211:8080/realms/auth/.well-known/openid-configuration"
